
// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'Web is not yet configured. ',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'iOS is not yet configured.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'macOS is not yet configured.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'Windows is not yet configured.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'Linux is not yet configured.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAmt_j1OZBivjS5i9gDN_ZPBTbG8Eo1-aM',
    appId: '1:85183874002:android:c46eb7b0082317f16bfe0b',
    messagingSenderId: '85183874002',
    projectId: 'lootha-c80cd',
    storageBucket: 'lootha-c80cd.firebasestorage.app',
  );
}
